# Generated by Django 4.1.5 on 2023-01-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.TextField()),
                ('name_ru', models.TextField()),
                ('serial_url', models.URLField()),
                ('serial_img', models.URLField()),
                ('serial_status', models.BooleanField()),
            ],
        ),
    ]
