# Generated by Django 4.1.5 on 2023-01-25 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name_en', models.TextField()),
                ('show_name_ru', models.TextField()),
                ('show_url', models.URLField()),
                ('show_img_url', models.URLField()),
                ('show_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_episode_name_ru', models.TextField()),
                ('last_episode_url', models.URLField()),
                ('last_news_name', models.TextField()),
                ('last_news_url', models.URLField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_info', to='app.show')),
                ('users', models.ManyToManyField(related_name='shows_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
