# Generated by Django 4.1.5 on 2023-01-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='show_name_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='show_name_ru',
            new_name='name_ru',
        ),
    ]
