# Generated by Django 4.1.5 on 2023-01-21 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_episode_name_ru', models.TextField()),
                ('last_episode_url', models.URLField()),
                ('last_news_name', models.TextField()),
                ('last_news_url', models.URLField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_information', to='app.serial')),
                ('users', models.ManyToManyField(related_name='shows_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
