# Generated by Django 4.1.5 on 2023-01-29 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_show_name_en_show_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showinfo',
            old_name='last_episode_name_ru',
            new_name='last_episode',
        ),
        migrations.RenameField(
            model_name='showinfo',
            old_name='last_news_name',
            new_name='last_news',
        ),
        migrations.RemoveField(
            model_name='show',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='showinfo',
            name='users',
        ),
        migrations.AddField(
            model_name='show',
            name='users',
            field=models.ManyToManyField(related_name='shows', to=settings.AUTH_USER_MODEL),
        ),
    ]
