# Generated by Django 4.1.5 on 2023-01-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_last_episode_name_ru_showinfo_last_episode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_img_url',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_status',
        ),
    ]
