# Generated by Django 4.1.5 on 2023-02-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_show_show_img_url_remove_show_show_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showinfo',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_info', to='app.show', unique=True),
        ),
    ]
