# Generated by Django 4.1.5 on 2023-02-08 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_showinfo_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='showinfo',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='show_info', serialize=False, to='app.show'),
        ),
    ]
